# Generated by Django 3.1.6 on 2021-02-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
